### PR TITLE
Add filter function to subset nodes and rels

### PR DESCRIPTION
**Pull request by WardCunningham**
The filter function is given the type and props of all elements and keeps those where the function returns true.

This sample from wiki mock graph.
http://ward.dojo.fed.wiki/fluent-macros.html

image

### CODE REVIEW

**Comment by WardCunningham** [comment]
I considered dereferencing the in, out, from, and to fields on behalf of the filtering predicate but dropped this idea for now. Hence the removal of the temps that I would use for that purpose.

**Comment by mkelleyharris** [comment]
Good progress.

TODO notes for kelley:
1)Look at Nodes & Rels classes in graph.js. Do they need to be exported, or just used internally. If exported, should they be test separately, and split into separate files?  

2)Study the n, o, f, t functions. Consider adding tests for those, or comments.

3) compare fluent use in fluent.test.js. Is it just a different use, or a potential wrapper around graphic? Since we have a fluent.test.js file, should we have a fluent.js class. Study it more.

**Comment by WardCunningham** [comment]
I've been working through the example queries I started a week ago recoding them with our current abstractions. I have found the "All Floyds" example useful and was pleased to make this invasive query work. 

image

A good challenge for us is to be sure that anything useful we can do with this unintended access can be done through an intended and tested interface.

Note: I have recalled this version from history as it has now been replaced. [wiki](http://ward.dojo.fed.wiki/view/fluent-macros_rev111)

**Comment by WardCunningham** [comment]
Where did all those Flores come from?

I recognized the name in a list of the top ten names in the dataset
```
curl -s http://ward.dojo.fed.wiki/assets/pages/mock-graph-data/graphs/raw.json | \
 jq -r '.organization[].name|split(" ")|.[2]' | \
 sort | uniq -c | sort -rn | head -10
 ```
 ```
   5 Ross
   5 Flores
   5 Bennett
   4 Foster
   4 Barnes
   3 White
   3 Sullivan
   3 Scott
   3 Murphy
   3 Morgan
   ```
I chose Flores over Ross and Bennett because of Fernando Flores and his association with Stafford Beers. Beers is a folk hero in my community due to his contributions to system science.
https://www.newyorker.com/magazine/2014/10/13/planning-machine

My fake data generator drew the name multiple times from this list:
https://github.com/WardCunningham/context-map-data/blob/master/ref/lastnames.json

I probably pulled that list out of a data generator I had written a few years before using data out of wikipedia:
https://en.wikipedia.org/wiki/List_of_most_common_surnames_in_North_America

**Pull request merged**
